apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: appstudio
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: dc-metro-map
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: dc-metro-map
  namespace: shebert
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: dc-metro-map
status:
  configuration:
    generatedName: ""
