apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-2
    app.kubernetes.io/part-of: appstudio
  name: java-springboot-2
  namespace: shebert
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-springboot-2
    weight: 100
status: {}
